### ISSUE TITLE
I used your code

### ISSUE THREAD

**Issue by gogo207** [abhinavabcd/QuizApp_Android#3]
I dont anderstand this 
`Take the service account id , and share the clones spread sheet sheet with that random email( this will enable api access to read from drive).`

**Comment by v-b-r** [comment]
Hi gogo, sorry for the late reply. You have to share the created spreadsheet with your service account id ( it should look something like 591807556804-t3rr9kac5adtclb86josfthmdq@**gserviceaccount.com). Alternatively you can make the newly created spreadsheet public (anyone with link can view/edit)
